[build]
builder = "nixpacks"

[nixpacks]
plan = "dotnet"

[nixpacks.variables]
DOTNET_VERSION = "8.0"

[nixpacks.build]
commands = [
  "dotnet restore",
  "dotnet build Commons/Commons.csproj -c Release",
  "dotnet build OrderManager/OrderManager.csproj -c Release",
  "dotnet publish OrderManager/OrderManager.csproj -c Release -o out"
]

[deploy]
start = "dotnet out/OrderManager.dll"
