//// <auto-generated />
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using OrderManager.DB;

//#nullable disable

//namespace OrderManager.Migrations
//{
//    [DbContext(typeof(OrderManagerDBContext))]
//    [Migration("20240408181944_AddClientiTable")]
//    partial class AddClientiTable
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.3")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("OrderManager.DB.Cliente", b =>
//                {
//                    b.Property<long>("ClienteId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClienteId"));

//                    b.Property<string>("CodiceCliente")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("CodiceFiscale")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Indirizzo")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Nome")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PartitaIva")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Telefono")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("ClienteId");

//                    b.ToTable("Clienti");
//                });

//            modelBuilder.Entity("OrderManager.DB.Prodotto", b =>
//                {
//                    b.Property<long>("ProdottoId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProdottoId"));

//                    b.Property<string>("Codice")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Descrizione")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<decimal>("Prezzo")
//                        .HasColumnType("decimal(18,2)");

//                    b.HasKey("ProdottoId");

//                    b.ToTable("Prodotti");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
